# docker-compose.yaml
version: '3.1'

services:
  gateway:
    build: ./gateway

  app_dccn_usermgr:
    build: ./app_dccn_usermgr
    ports:
    - 50051:50051
    environment:
      MICRO_ADRESS: ":50051"
      MICRO_BROKER: "rabbitmq"
      DB_HOST: "datastore:27017"

  app_dccn_dcmgr:
    build: ./app_dccn_dcmgr
    ports:
    - 50052:50052
    environment:
      MICRO_SERVER_ADDRESS: ":50052"
      MICRO_TRANSPORT: "nats"
      MICRO_BROKER: "rabbitmq"
      MICRO_REGISTRY: "kubernetes"
      DB_HOST: "datastore:27017"

  app_dccn_taskmgr:
    build: ./app_dccn_taskmgr
    ports:
    - 50053:50053
    environment:
      MICRO_ADRESS: ":50053"
      MICRO_TRANSPORT: "nats"
      MICRO_BROKER: "rabbitmq"
      MICRO_REGISTRY: "kubernetes"
      DB_HOST: "datastore:27017"

  user-service:
    build: ./user-service
    ports:
    - 50053:50051
    environment:
      MICRO_ADRESS: ":50051"
      MICRO_REGISTRY: "mdns"
      DB_NAME: "postgres"
      DB_HOST: "database"
      DB_PORT: "5432"
      DB_USER: "postgres"
      DB_PASSWORD: "postgres"
    depends_on:
    - database

  datastore:
    image: mongo
    ports:
    - 27017:27017

  broker:
    image: rabbitmq
    ports:
      -5672:5672
      -15672:15672

  micro:
    image: microhq/micro
    ports:
      -8080:8080


