# docker-compose.yaml
version: '3.1'

services:

  rabbitmq:
    image: rabbitmq
    container_name: dccn-broker-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  datastore:
    image: mongo
    container_name: dccn-datastore-mongo
    ports:
        - "27017:27017"

  consul:
    image: consul:latest
    container_name: dccn-registry-consul
    command: agent -server -bootstrap -rejoin -ui -client 0.0.0.0
    ports:
        - "8300:8300"
        - "8400:8400"
        - "8500:8500"
        - "8600:53/udp"

  micro:
    # command: --registry_address="consul:8500" --enable_stats --register_interval=5 --register_ttl=10 api --handler=rpc
    command: --registry="mdns" --enable_stats --register_interval=5 --register_ttl=10 api --handler=rpc
    image: microhq/micro:latest
    # depends_on: 
        # - consul
    links:
        # - consul
        - usermgr
        - dcmgr
    ports:
        - "8080:8080"

  usermgr:
    image: app-dccn-v1-usermgr
    container_name: app-dccn-v1-usermgr
    build:
        context: .
        dockerfile: dockerfile/usermgr.Dockerfile
    ports:
        - "50051:50051"
    environment:
        MICRO_SERVER_NAME: "go.micro.srv.v1.usermgr"
        MICRO_REGISTRY: "consul"
        MICRO_REGISTRY_ADDRESS: "localhost:8500"
        MICRO_ADRESS: ":50051"
        MICRO_SERVER_VERSION: "v1.0"
        MICRO_REGISTER_TTL: 5
        MICRO_REGISTER_INTERVAL: 5
        DB_HOST: "datastore:27017"
        DB_NAME: "dccn"
        DB_COLLECTION: "user"
        DB_TIMEOUT: 5
        DB_POOL_LIMIT: 4096
        TOKEN_ACTIVE_TIME: 20
    depends_on:
        - datastore

  usermgr-client:
    image: app-dccn-v1-usermgr-client
    container_name: app-dccn-v1-usermgr-client
    build:
        context: .
        dockerfile: dockerfile/usermgr_client.Dockerfile
    environment:
        MICRO_REGISTRY_ADDRESS: "localhost:8500"
    depends_on:
        - datastore
        # - consul

  dcmgr:
    image: app-dccn-v1-dcmgr
    container_name: app-dccn-v1-dcmgr
    build:
        context: .
        dockerfile: dockerfile/dcmgr.Dockerfile
    ports:
        - "50052:50052"
    environment:
        MICRO_REGISTRY: "mdns"
        # MICRO_REGISTRY_ADDRESS: "consul:8500"
        MICRO_SERVER_NAME: "go.micro.srv.v1.dcmgr"
        MICRO_ADRESS: ":50052"
        MICRO_SERVER_VERSION: "v1.0"
        MICRO_REGISTER_TTL: 5
        MICRO_REGISTER_INTERVAL: 5
        DB_HOST: "datastore:27017"
        DB_NAME: "dccn"
        DB_COLLECTION: "dc"
        DB_TIMEOUT: 5
        DB_POOL_LIMIT: 4096
        TOKEN_ACTIVE_TIME: 20
    depends_on:
        # - consul
        - datastore
    links:
        # - consul
        - datastore

  dcmgr-client:
    image: app-dccn-v1-dcmgr-client
    container_name: app-dccn-v1-dcmgr-client
    build:
        context: .
        dockerfile: dockerfile/dcmgr_client.Dockerfile
    environment:
        MICRO_REGISTRY: "mdns"
        # MICRO_REGISTRY_ADDRESS: "consul:8500"
    depends_on:
        # - consul
        - datastore
    # links:
    #     - consul

  taskmgr:
    build: ./app_dccn_taskmgr
    ports:
        - 50053:50053
    environment:
      MICRO_ADRESS: ":50053"
      DB_HOST: "datastore:27017"