# docker-compose.yaml
version: '3.7'

services:

  broker:
    image: rabbitmq:management
    container_name: dccn-broker-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  datastore:
    image: mongo:latest
    container_name: dccn-mongo
    ports:
      - "27017:27017"

  micro:
    image: microhq/micro:latest
    command: --registry=mdns --enable_stats --register_interval=5 --register_ttl=10 --register_interval=10 app-dccn-api --handler=rpc
    ports:
      - "8080:8080"

  taskmgr:
    image: app-dccn-taskmgr
    container_name: app-dccn-taskmgr
    build:
      context: .
      dockerfile: ./dockerfile/task.Dockerfile
    environment:
      MICRO_REGISTRY: mdns
      MICRO_BROKER: rabbitmq
      MICRO_BROKER_ADDRESS: amqp://guest:guest@broker:5672
      MICRO_SERVER_VERSION: v1.0
      MICRO_REGISTER_TTL: 15
      MICRO_REGISTER_INTERVAL: 15
      DB_HOST: datastore:27017
      DB_NAME: dccn
      DB_COLLECTION: task
      DB_TIMEOUT: 5
      DB_POOL_LIMIT: 4096
#      DISABLE_AUTH: "true"
    links:
      - broker
      - datastore

  usermgr:
    image: app-dccn-usermgr
    container_name: app-dccn-usermgr
    build:
      context: .
      dockerfile: ./dockerfile/user.Dockerfile
    environment:
      MICRO_REGISTRY: mdns
      MICRO_SERVER_VERSION: v1.0
      MICRO_REGISTER_TTL: 15
      MICRO_REGISTER_INTERVAL: 15
      DB_HOST: datastore:27017
      DB_NAME: dccn
      DB_COLLECTION: user
      DB_TIMEOUT: 5
      DB_POOL_LIMIT: 4096
    links:
      - datastore

  email:
    image: app-dccn-email
    container_name: app-dccn-email
    build:
      context: .
      dockerfile: ./dockerfile/email.Dockerfile
    environment:
      MICRO_REGISTRY: mdns
      MICRO_BROKER: rabbitmq
      MICRO_BROKER_ADDRESS: amqp://guest:guest@broker:5672
      MICRO_SERVER_VERSION: v1.0
      MICRO_REGISTER_TTL: 15
      MICRO_REGISTER_INTERVAL: 15
      DB_HOST: datastore:27017
      DB_NAME: dccn
      DB_COLLECTION: user
      DB_TIMEOUT: 5
      DB_POOL_LIMIT: 4096
    links:
      - broker
      - datastore

  api:
    image: app-dccn-api
    container_name: app-dccn-api
    build:
      context: .
      dockerfile: ./dockerfile/api.Dockerfile
    environment:
      MICRO_REGISTRY: mdns
      MICRO_SERVER_ADDRESS: :50051
      MICRO_BROKER: rabbitmq
      MICRO_BROKER_ADDRESS: amqp://guest:guest@broker:5672
      MICRO_SERVER_VERSION: v1.0
      MICRO_REGISTER_TTL: 15
      MICRO_REGISTER_INTERVAL: 15
      DB_HOST: datastore:27017
      DB_NAME: dccn
      DB_COLLECTION: datacenter
      DB_TIMEOUT: 5
      DB_POOL_LIMIT: 4096
      DISABLE_AUTH: "true"
    ports:
      - "50051:50051"
    links:
      - taskmgr
      - email
      - usermgr
      - broker
      - datastore

