#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true

# UPGRADE: Protobuf


# Required: Protobuf is required by gRPC
[[constraint]]
  branch = "master"
  name = "github.com/streadway/amqp"

# Required: net.context is required by gRPC
[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

# UPGRADE: Protobuf

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.17.0"

# UPGRADE: Protobuf

[[constraint]]
  branch = "v2"
  name = "gopkg.in/mgo.v2"

[prune]
  go-tests = true
  unused-packages = true
