apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: usermgr
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: usermgr
    spec:
      imagePullSecrets:
      - name: dccn-ecr
      containers:
      - image: 815280425737.dkr.ecr.us-west-2.amazonaws.com/app_dccn_usermgr:latest
        imagePullPolicy: "Always"
        name: usermgr
