apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: user-manager
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: user-manager
    spec:
      imagePullSecrets:
      - name: dccn-ecr
      containers:
      - image: 815280425737.dkr.ecr.us-west-2.amazonaws.com/dccn-hub-user-manager:stage20181222041227
        imagePullPolicy: "Always"
        name: user-manager
