version: 2
jobs:
  build:
    docker:
      # Build in Python container to install AWS CLI
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/Ankr-network/dccn-hub
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: copy ssh key
          command: |
            cp ${HOME}/.ssh/id_rsa id_rsa
      - run:
          name: Install AWSCLI
          command: |
            curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
            unzip awscli-bundle.zip
            sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
      - run:
          name: "Log in to AWS ECR"
          command: eval $(aws ecr get-login --no-include-email --region us-west-2)
      - run:
          name: "Build & Push Docker Image"
          command: |
            docker build -f Dockerfile_API_Listener -t dccn-hub_api_listener .
            docker tag dccn-hub_api_listener:latest 815280425737.dkr.ecr.us-west-2.amazonaws.com/dccn_ecr:dccn-hub_api_listener
            docker push 815280425737.dkr.ecr.us-west-2.amazonaws.com/dccn_ecr:dccn-hub_api_listener

            docker build -f Dockerfile_TaskManager -t dccn-hub_task_manager .
            docker tag dccn-hub_task_manager:latest 815280425737.dkr.ecr.us-west-2.amazonaws.com/dccn_ecr:dccn-hub_task_manager
            docker push 815280425737.dkr.ecr.us-west-2.amazonaws.com/dccn_ecr:dccn-hub_task_manager

            docker build -f Dockerfile_K8s_Adapter -t dccn-hub_k8s_adapter .
            docker tag dccn-hub_k8s_adapter:latest 815280425737.dkr.ecr.us-west-2.amazonaws.com/dccn_ecr:dccn-hub_k8s_adapter
            docker push 815280425737.dkr.ecr.us-west-2.amazonaws.com/dccn_ecr:dccn-hub_k8s_adapter
