apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: taskmgr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskmgr
  template:
    metadata:
      labels:
        app: taskmgr
    spec:
      containers:
      - name: taskmgr-service
        image: 815280425737.dkr.ecr.us-west-2.amazonaws.com/app_dccn_dmmgr:latest
        imagePullPolicy: Always
        command: [
          "./shippy-taskmgr-service",
          "--selector=static",
          "--server_address=:8080"
        ]
        env:
        - name: DB_HOST
          value: "mongo:27017"
        ports:
        - containerPort: 8080
          name: taskmgr-port
