apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: ankr-hub
  name: hub
spec:
  replicas: 1
  selector:
    name: hub
  template:
    metadata:
      labels:
        name: hub
    spec:
      imagePullSecrets:
      - name: dccn-ecr
      containers:
      - image: 815280425737.dkr.ecr.us-west-2.amazonaws.com/dccn_ecr:dccn-hub
        imagePullPolicy: "Always"
        name: hub
        ports:
        - containerPort: 50051
          name: hub-port