apiVersion: v1
kind: Service
metadata:
  name: hub-service
  labels:
    name: hub-service
spec:
  type: LoadBalancer
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP
  selector:
    name: hub