apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dccn-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dccn-api
  template:
    metadata:
      labels:
        app: dccn-api
    spec:
        containers:
        - name: dccn-api
          image: dccn-api
#          imagePullPolicy: Always
#          不要拉取镜像,Always为默认值
          imagePullPolicy: IfNotPresent
          command: [ "/api" ]
          env:
          - name: DB_COLLECTION
            value: datacenter
          - name: DB_HOST
            value: "datastore:27017"
          - name: DB_NAME
            value: dccn
          - name: DB_POOL_LIMIT
            value: "4096"
          - name: DB_TIMEOUT
            value: "5"
          - name: MICRO_BROKER
            value: rabbitmq
          - name: MICRO_BROKER_ADDRESS
            value: amqp://guest:guest@broker:5672
          - name: MICRO_REGISTER_INTERVAL
            value: "15"
          - name: MICRO_REGISTRY
            value: consul
          - name: MICRO_REGISTRY_ADDRESS
            value: consul:8500
          - name: MICRO_SERVER_ADDRESS
            value: :50051
          - name: MICRO_SERVER_VERSION
            value: v1.0
          ports:
          - containerPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: dccn-api
  labels:
    app: dccn-api
spec:
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP
  selector:
    app: dccn-api
