kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongopvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 16Gi
  storageClassName: gp2
