apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: consul
  name: consul
spec:
  ports:
  - name: "8300"
    port: 8300
    targetPort: 8300
  - name: "8400"
    port: 8400
    targetPort: 8400
  - name: "8500"
    port: 8500
    targetPort: 8500
  - name: "8600"
    port: 8600
    protocol: UDP
    targetPort: 53
  selector:
    io.kompose.service: consul
status:
  loadBalancer: {}
