apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yaml
    kompose.version: 1.17.0 (a74acad)
  creationTimestamp: null
  labels:
    io.kompose.service: email
  name: email
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: email
    spec:
      imagePullSecrets:
      - name: aws-ecr
      containers:
      - env:
        - name: DB_COLLECTION
          value: user
        - name: DB_HOST
          value: datastore:27017
        - name: DB_NAME
          value: dccn
        - name: DB_POOL_LIMIT
          value: "4096"
        - name: DB_TIMEOUT
          value: "5"
        - name: MICRO_BROKER
          value: rabbitmq
        - name: MICRO_BROKER_ADDRESS
          value: amqp://guest:guest@broker:5672
        - name: MICRO_REGISTER_INTERVAL
          value: "15"
        - name: MICRO_REGISTER_TTL
          value: "600"
        - name: MICRO_REGISTRY
          value: consul
        - name: MICRO_REGISTRY_ADDRESS
          value: consul:8500
        - name: MICRO_SERVER_VERSION
          value: v1.0
        image: "815280425737.dkr.ecr.us-west-2.amazonaws.com/dccn-hub-email:feat"
        name: app-dccn-email
        resources: {}
      restartPolicy: Always
status: {}
