apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dccn-email
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dccn-email
  template:
    metadata:
      labels:
        app: dccn-email
    spec:
        containers:
        - name: dccn-email
          image: 815280425737.dkr.ecr.us-west-2.amazonaws.com/dccn-hub-email:feat
#          imagePullPolicy: Always
#          不要拉取镜像,Always为默认值
          imagePullPolicy: IfNotPresent
          command: [ "/email" ]
          env:
          - name: MICRO_REGISTER_INTERVAL
            value: "15"
          - name: MICRO_REGISTRY
            value: consul
          - name: MICRO_REGISTRY_ADDRESS
            value: consul:8500
          - name: MICRO_SERVER_VERSION
            value: v1.0
