apiVersion: v1
kind: Service
metadata:
  name: k8s-adapter-service
  labels:
    name: k8s-adapter-service
spec:
  type: LoadBalancer
  ports:
    - port: 50052
      targetPort: 50052
      protocol: TCP
  selector:
    name: k8s-adapter