apiVersion: v1
kind: Service
metadata:
  name: micro
  labels:
    name: micro
spec:
  type: LoadBalancer
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP
  selector:
    name: micro
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: micro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: micro
  template:
    metadata:
      labels:
        name: micro
    spec:
      imagePullSecrets:
      - name: dccn-ecr
      containers:
      - image: microhq/micro:kubernetes
        ports:
        - containerPort: 50051