apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: broker-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 16Gi
  storageClassName: gp2
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: broker
  name: broker
spec:
  ports:
    - port: 5672
      targetPort: 5672
    - port: 15672
      targetPort: 15672
  selector:
    name: broker
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: broker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: broker
    spec:
      containers:
      - image: rabbitmq:3-management
        name: broker
        ports:
        - name: broker
          containerPort: 5672
          hostPort: 5672
        - name: broker-ma
          containerPort: 15672
          hostPort: 15672
        volumeMounts:
          - name: broker-data
            mountPath: /var/lib/rabbitmq
      volumes:
        - name: broker-data
          persistentVolumeClaim:
            claimName: broker-pvc
