apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dccn-task
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dccn-task
  template:
    metadata:
      labels:
        app: dccn-task
    spec:
        containers:
        - name: dccn-task
          image: 815280425737.dkr.ecr.us-west-2.amazonaws.com/dccn-hub-taskmgr:feat
          imagePullPolicy: Always
          command: [ "/taskmgr" ]
          env:
          - name: DB_COLLECTION
            value: task
          - name: DB_HOST
            value: datastore:27017
          - name: DB_NAME
            value: dccn
          - name: DB_POOL_LIMIT
            value: "4096"
          - name: DB_TIMEOUT
            value: "5"
          - name: MICRO_BROKER
            value: rabbitmq
          - name: MICRO_BROKER_ADDRESS
            value: amqp://guest:guest@broker:5672
          - name: MICRO_REGISTER_INTERVAL
            value: "15"
          - name: MICRO_REGISTRY
            value: consul
          - name: MICRO_REGISTRY_ADDRESS
            value: consul:8500
          - name: MICRO_SERVER_VERSION
            value: v1.0
