apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: task-manager
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: task-manager
    spec:
      imagePullSecrets:
      - name: dccn-ecr
      containers:
      - image: 815280425737.dkr.ecr.us-west-2.amazonaws.com/dccn-hub-task-manager:feat
        imagePullPolicy: "Always"
        name: task-manager
